language: node_js
node_js:
  - "8"
script:
  - echo 'Build starts!'
  - echo 'Testing...'
  - npm run test
  - echo 'Linting...'
  - npm run lint
  - echo 'Building...'
  - npm run build
cache:
  directories:
    - node_modules
